# This code computes prime numbers, their positons in the prime hexagon,
# the polarity of the number, and the prime hexagon's overall rotation.
#
# Usage:
# python ./primespin.py --nvalues=1000 --chunks 100 --save-text
#
# For more information see: 
# https://github.com/chetabahana/hexagon#prime-hexagon

name: Prime Hexagon

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!backup'
      - '!Chetabahana'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Primes Spins
      run: |
        printenv
        cd $GITHUB_WORKSPACE && ls -al
        python -m pip install --upgrade pip
        pip install numpy primesieve pytest
        PYTHONPATH=. pytest -v --debug tests/test_prime_hex.py
